language: go
env:
- GO111MODULE=on
go:
  - 1.11.x
  - master

install:
  - go get github.com/mattn/goveralls
  - go get -u github.com/golang/lint/golint
  - go install

script:
  - go build github.com/flowup/mmo
  - golint $(go list -e github.com/flowup/mmo/... | grep -v templates)
  # - $HOME/gopath/bin/goveralls -service=travis-ci