apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Name }}
  namespace: equimo
  labels:
    app: {{ .Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Name }}
  template:
    metadata:
      labels:
        app: {{ .Name }}
        type: api-service
    spec:
      containers:
      - name: {{ .Name }}
        image: {{ .Project }}-{{ .Name }}:latest
        command: ['./{{ .Name }}']
        env:
        - name: PORT_LEN
          value: {{ len .k.Ports}}
        ports: {{range $index, $element := .k.Ports}}
        - name: {{ $element.Name }}
          containerPort: {{ $element.Number }}
          protocol: TCP {{end}}