kind: Service
apiVersion: v1
metadata:
  name: {{ .Name }}
spec:
  selector:
    app: {{ .Name }}
  ports:{{range $index, $element := .k.Ports}}
    - name: {{ $element.Name }}
      port: {{ $element.Number }}
      protocol: TCP {{end}}